name: xseed_dependency_updater
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1
  http: ^1.2.0
  process_run: ^0.14.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
